# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistran', '0006_auto_20160712_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos/%Y/%m/%D', verbose_name='arquivo')),
                ('tipo_documento', models.CharField(choices=[(None, 'Escolha uma opção'), ('alvara', 'Alvará'), ('transferencia', 'Transferência')], max_length=30, verbose_name='tipo de documento')),
                ('codigo', models.CharField(max_length=50, verbose_name='código hash')),
                ('codigo_verificador', models.CharField(max_length=5, verbose_name='código verificador')),
                ('data_emissao', models.DateField(verbose_name='data da emissão')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.Permissao')),
            ],
        ),
    ]
