# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='permissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.PermissaoTemProprietario'),
        ),
    ]
