# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0004_auto_20160317_1108'),
    ]

    operations = [
    ]
