# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessoria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('assessoria', models.CharField(max_length=255)),
                ('contato_telefonico', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'assessoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=255)),
                ('moeda_salario', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('celula', models.CharField(max_length=255)),
                ('contato_telefonico', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'celula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=255)),
                ('vinculo', models.CharField(blank=True, max_length=255, null=True)),
                ('turno', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lotacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contato_telefonico', models.CharField(max_length=255)),
                ('organismo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'organismo',
                'managed': False,
            },
        ),
    ]
