# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoCidadao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_documento', models.CharField(max_length=255)),
                ('caminho', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoPermissao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_documento', models.CharField(max_length=255)),
                ('caminho', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoal.Cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoal.Cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_permissao', models.IntegerField(blank=True, null=True, verbose_name='Número da Permissão')),
                ('data', models.DateField(auto_now=True)),
                ('tipo_concessao', models.CharField(choices=[('TÁXI', 'TÁXI'), ('ALTERNATIVO', 'ALTERNATIVO'), ('ESCOLAR', 'ESCOLAR'), ('FRETE', 'FRETE')], max_length=20, verbose_name='Tipo do Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoTemCobrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_posse', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=10)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.Cobrador')),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoTemMotorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_posse', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=10)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.Motorista')),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoTemProprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_posse', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('TRANSFERIDO', 'TRANSFERIDO'), ('INATIVO', 'INATIVO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoTemVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_posse', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('TRANSFERIDO', 'TRANSFERIDO'), ('INATIVO', 'INATIVO')], max_length=10)),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.Permissao')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoal.Cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('codigo_renavan', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Código Renavan')),
                ('veiculo_proprio', models.BooleanField(default=True)),
                ('exercicio', models.CharField(max_length=255, verbose_name='Ano de Exercício')),
                ('placa', models.CharField(max_length=8, verbose_name='Placa do Veículo')),
                ('chassi', models.CharField(max_length=255, verbose_name='Chassi do Veículo')),
                ('num_passageiros', models.IntegerField(verbose_name='Número de Passageiros')),
                ('combustivel', models.CharField(max_length=255, verbose_name='Combustível')),
                ('marca', models.CharField(choices=[('AGRALE', 'AGRALE'), ('ASTON MARTIN', 'ASTON MARTIN'), ('AUDI', 'AUDI'), ('BENTLEY', 'BENTLEY'), ('BMW', 'BMW'), ('CHANGAN', 'CHANGAN'), ('CHERY', 'CHERY'), ('CHEVROLET', 'CHEVROLET'), ('CHRYSLER', 'CHRYSLER'), ('CITROËN', 'CITROËN'), ('DODGE', 'DODGE'), ('EFFA', 'EFFA'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('GEELY', 'GEELY'), ('HAFEI', 'HAFEI'), ('HONDA', 'HONDA'), ('HYUNDAI', 'HYUNDAI'), ('IVECO', 'IVECO'), ('JAC MOTORS', 'JAC MOTORS'), ('JAGUAR', 'JAGUAR'), ('JEEP', 'JEEP'), ('JINBEI', 'JINBEI'), ('KIA', 'KIA'), ('LAMBORGHINI', 'LAMBORGHINI'), ('LAND ROVER', 'LAND ROVER'), ('LEXUS', 'LEXUS'), ('LIFAN', 'LIFAN'), ('MAHINDRA', 'MAHINDRA'), ('MASERATI', 'MASERATI'), ('MERCEDES-BENZ', 'MERCEDES-BENZ'), ('MG MOTORS', 'MG MOTORS'), ('MINI', 'MINI'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('PEUGEOT', 'PEUGEOT'), ('PORSCHE', 'PORSCHE'), ('RAM', 'RAM'), ('RENAULT', 'RENAULT'), ('SMART', 'SMART'), ('SSANGYONG', 'SSANGYONG'), ('SUBARU', 'SUBARU'), ('SUZUKI', 'SUZUKI'), ('TOYOTA', 'TOYOTA'), ('TROLLER', 'TROLLER'), ('VOLKSWAGEN', 'VOLKSWAGEN'), ('VOLVO', 'VOLVO')], max_length=255, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('ano_fabricacao', models.CharField(max_length=255, verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.CharField(max_length=255, null=True, verbose_name='Ano do Modelo')),
                ('categoria', models.CharField(choices=[('OFICIAL', 'OFICIAL'), ('REPRESENTAÇÃO DIPLOMÁTICA', 'REPRESENTAÇÃO DIPLOMÁTICA'), ('PARTICULAR', 'PARTICULAR'), ('ALUGUEL', 'ALUGUEL'), ('APRENDIZAGEM', 'APRENDIZAGEM')], max_length=155, verbose_name='Categoria')),
                ('cor_predominante', models.CharField(choices=[('BRANCA', 'BRANCA'), ('PRATA', 'PRATA'), ('PRETA', 'PRETA'), ('CINZA', 'CINZA'), ('VERMELHA', 'VERMELHA'), ('MARROM', 'MARROM'), ('BEGE', 'BEGE'), ('AZUL', 'AZUL'), ('VERDE', 'VERDE'), ('AMARELA', 'AMARELA'), ('DOURADA', 'DOURADA')], max_length=255, verbose_name='Cor Predominante')),
            ],
        ),
        migrations.AddField(
            model_name='permissaotemveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.Veiculo'),
        ),
        migrations.AddField(
            model_name='permissaotemproprietario',
            name='permissao_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.PermissaoTemVeiculo'),
        ),
        migrations.AddField(
            model_name='permissaotemproprietario',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.Proprietario'),
        ),
        migrations.AddField(
            model_name='permissaotemmotorista',
            name='permissao_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.PermissaoTemVeiculo'),
        ),
        migrations.AddField(
            model_name='permissaotemcobrador',
            name='permissao_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.PermissaoTemVeiculo'),
        ),
        migrations.AddField(
            model_name='anexopermissao',
            name='permissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistran.Permissao'),
        ),
        migrations.AddField(
            model_name='anexocidadao',
            name='cidadao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Cidadao'),
        ),
    ]
