# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistran', '0003_auto_20160225_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='ordem_servico',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='sistran.OrdemServico'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
