# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistran', '0004_auto_20160225_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistoria',
            name='data',
        ),
        migrations.AddField(
            model_name='vistoria',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='aprovado'),
        ),
    ]
